[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x7f3ae67517b7a11d25927d974900e6ff99ad9edbcdb492b7a4dca44ade6f8fbf'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]